name: Build and Push to ECR

on:
  push:
  pull_request:

env:
  AWS_REGION: us-east-1 
  ECR_REPOSITORY: learn-ecs
  ECR_REGISTRY: 286812073492.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Jenkins to Amazon ECR
      run: |
        # Extract the branch name from GITHUB_REF
        BRANCH_NAME=${GITHUB_REF##*/}

        # Build the Docker image and tag it with the branch name and latest
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_NAME -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f docker/Dockerfile .

    - name: Push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      if: github.ref == 'refs/heads/main' || github.event_name == "pull_request"
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG