name: 'Security Scanning'

on:
  pull_request:

permissions:
  contents: read
  pull-requests	: write

jobs:
  trivy-iac:
    name: "Trivy IAC Scan"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@0.24.0
      with:
        scan-type: 'config'
        hide-progress: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

  trivy-image:
    name: 'Trivy Image Scan'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Jenkins Docker Image
      run: docker build -t jenkins:${{ github.sha }} . 
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: 'jenkins:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'