name: 'Security Scanning'

on:
  pull_request:

permissions:
  contents: read
  pull-requests	: write

jobs:
  trivy-iac:
    name: "Trivy IaC Scan"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@0.24.0
      with:
        scan-type: 'config'
        hide-progress: true
        format: 'sarif'
        output: 'trivy-iac-results.sarif'
        ignore-unfixed: true
        exit-code: '1'
        config-path: trivy.yaml

    - name: Upload Trivy Results
      id: upload-trivy-iac-artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-iac-results
        path: trivy-iac-results.sarif

    - name: Comment Trivy Results
      if: always() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: `Trivy IaC scan uploaded: [IaC Scan Report](${{ steps.upload-trivy-iac-artifact.outputs.artifact-url }})`
          })

  trivy-image:
    name: 'Trivy Image Scan'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Jenkins Docker Image
      run: docker build -t jenkins:${{ github.sha }} -f docker/Dockerfile . 
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: 'jenkins:${{ github.sha }}'
        format: 'table'
        ignore-unfixed: true
        output: 'trivy-image-results.sarif'
        vuln-type: 'os,library'
        exit-code: '1'
        trivy-config: trivy.yaml

    - name: Upload Trivy Results
      id: upload-trivy-image-artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: trivy-image-results
        path: trivy-image-results.sarif

    - name: Comment Trivy Results
      if: always() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: `Trivy image scan uploaded: [image Scan Report](${{ steps.upload-trivy-image-artifact.outputs.artifact-url }})`
          })